import { describe, it, expect } from 'vitest'
import { detectTypeByFilename, detectTypeByContent, detectProjectType } from './detector'

describe('detector 文件类型检测', () => {
  describe('detectTypeByFilename 按文件名识别', () => {
    it('package.json → npm', () => {
      expect(detectTypeByFilename('package.json')).toBe('npm')
    })

    it('requirements.txt → pip', () => {
      expect(detectTypeByFilename('requirements.txt')).toBe('pip')
    })

    it('requirements-dev.txt → pip', () => {
      expect(detectTypeByFilename('requirements-dev.txt')).toBe('pip')
    })

    it('pyproject.toml → poetry', () => {
      expect(detectTypeByFilename('pyproject.toml')).toBe('poetry')
    })

    it('yarn.lock → lockfile', () => {
      expect(detectTypeByFilename('yarn.lock')).toBe('lockfile')
    })

    it('pnpm-lock.yaml → lockfile', () => {
      expect(detectTypeByFilename('pnpm-lock.yaml')).toBe('lockfile')
    })

    it('package-lock.json → lockfile', () => {
      expect(detectTypeByFilename('package-lock.json')).toBe('lockfile')
    })

    it('.env → env', () => {
      expect(detectTypeByFilename('.env')).toBe('env')
    })

    it('.env.production → env', () => {
      expect(detectTypeByFilename('.env.production')).toBe('env')
    })

    it('myapp.env → env', () => {
      expect(detectTypeByFilename('myapp.env')).toBe('env')
    })

    it('config.env.local → env', () => {
      expect(detectTypeByFilename('config.env.local')).toBe('env')
    })

    it('未知文件名 → null', () => {
      expect(detectTypeByFilename('pasted.txt')).toBeNull()
      expect(detectTypeByFilename('config.json')).toBeNull()
      expect(detectTypeByFilename('data.yaml')).toBeNull()
    })

    it('文件名大小写不敏感', () => {
      expect(detectTypeByFilename('PACKAGE.JSON')).toBe('npm')
      expect(detectTypeByFilename('Requirements.TXT')).toBe('pip')
    })
  })

  describe('detectTypeByContent 按内容识别', () => {
    it('空内容 → env', () => {
      expect(detectTypeByContent('')).toBe('env')
      expect(detectTypeByContent('   ')).toBe('env')
    })

    it('含 dependencies 的 JSON → npm', () => {
      const content = JSON.stringify({ name: 'app', dependencies: { react: '^18' } })
      expect(detectTypeByContent(content)).toBe('npm')
    })

    it('仅含 name+version 的 JSON → npm', () => {
      const content = JSON.stringify({ name: 'app', version: '1.0.0' })
      expect(detectTypeByContent(content)).toBe('npm')
    })

    it('非法 JSON 不判为 npm', () => {
      expect(detectTypeByContent('{ invalid json')).toBe('env')
    })

    it('含 [project] → poetry', () => {
      expect(detectTypeByContent('[project]\nname = "app"')).toBe('poetry')
    })

    it('含 [tool.poetry] → poetry', () => {
      expect(detectTypeByContent('[tool.poetry]\nname = "app"')).toBe('poetry')
    })

    it('含 build-backend → poetry', () => {
      expect(detectTypeByContent('[build-system]\nbuild-backend = "poetry.core.masonry.api"')).toBe('poetry')
    })

    it('含 package==1.0 → pip', () => {
      expect(detectTypeByContent('package==1.0.0')).toBe('pip')
    })

    it('含 package>=1.0 → pip', () => {
      expect(detectTypeByContent('package>=1.0,<2.0')).toBe('pip')
    })

    it('yarn.lock 自动生成头 → lockfile', () => {
      expect(detectTypeByContent('# THIS IS AN AUTOGENERATED FILE')).toBe('lockfile')
    })

    it('含 yarn lockfile 注释 → lockfile', () => {
      expect(detectTypeByContent('# yarn lockfile v1\nlodash@^4.0.0:')).toBe('lockfile')
    })

    it('含 lockfileVersion → lockfile', () => {
      expect(detectTypeByContent('lockfileVersion: 3')).toBe('lockfile')
    })

    it('普通 KEY=VALUE → env', () => {
      expect(detectTypeByContent('API_KEY=abc123\nPORT=3000')).toBe('env')
    })
  })

  describe('detectProjectType 综合检测', () => {
    it('强信号文件名直接采信', () => {
      expect(detectProjectType('package.json', '')).toBe('npm')
      expect(detectProjectType('requirements.txt', '')).toBe('pip')
      expect(detectProjectType('pyproject.toml', '')).toBe('poetry')
      expect(detectProjectType('yarn.lock', '')).toBe('lockfile')
    })

    it('中性文件名 + JSON 内容 → npm（优先看内容）', () => {
      const content = JSON.stringify({ name: 'app', dependencies: { react: '^18' } })
      expect(detectProjectType('pasted.env', content)).toBe('npm')
      expect(detectProjectType('pasted.txt', content)).toBe('npm')
    })

    it('中性文件名 + requirements 内容 → pip', () => {
      expect(detectProjectType('pasted.env', 'flask==2.0.0')).toBe('pip')
    })

    it('中性文件名 + pyproject 内容 → poetry', () => {
      expect(detectProjectType('pasted.env', '[project]\nname = "app"')).toBe('poetry')
    })

    it('中性文件名 + lockfile 内容 → lockfile', () => {
      expect(detectProjectType('pasted.env', 'lockfileVersion: 3')).toBe('lockfile')
    })

    it('.env 文件名 + .env 内容 → env', () => {
      expect(detectProjectType('.env', 'API_KEY=abc123')).toBe('env')
    })

    it('未知文件名 + .env 内容 → env', () => {
      expect(detectProjectType('pasted.txt', 'API_KEY=abc123')).toBe('env')
    })

    it('未知文件名 + 空内容 → env（默认）', () => {
      expect(detectProjectType('pasted.txt', '')).toBe('env')
    })

    it('memory 约束：pasted.env 命名但内容是 JSON → npm（不因文件名误判为 env）', () => {
      const content = JSON.stringify({ name: 'app', dependencies: { react: '^18' } })
      expect(detectProjectType('pasted.env', content)).toBe('npm')
    })

    it('.env.production + .env 内容 → env', () => {
      expect(detectProjectType('.env.production', 'API_KEY=abc123\nPORT=3000')).toBe('env')
    })
  })
})
