// 文件类型检测：根据文件名与内容判断项目类型
import type { ProjectType } from '../../types'

/** 根据文件名判断项目类型 */
export function detectTypeByFilename(filename: string): ProjectType | null {
  const name = filename.toLowerCase()
  if (name === 'package.json') return 'npm'
  if (name === 'requirements.txt' || name.startsWith('requirements-')) return 'pip'
  if (name === 'pyproject.toml') return 'poetry'
  if (name === 'yarn.lock' || name === 'pnpm-lock.yaml' || name === 'package-lock.json')
    return 'lockfile'
  if (name.startsWith('.env') || name.endsWith('.env') || name.includes('.env.')) return 'env'
  return null
}

/** 根据内容进一步判断项目类型（文件名无法识别时使用） */
export function detectTypeByContent(content: string): ProjectType {
  const trimmed = content.trim()
  if (!trimmed) return 'env'

  // JSON：尝试解析为 package.json
  if (trimmed.startsWith('{')) {
    try {
      const obj = JSON.parse(trimmed)
      if (obj && typeof obj === 'object' && ('dependencies' in obj || 'devDependencies' in obj || 'name' in obj && 'version' in obj)) {
        return 'npm'
      }
    } catch {
      // 非合法 JSON，继续判断
    }
  }

  // TOML：pyproject.toml 标志性字段
  if (trimmed.startsWith('#') || trimmed.includes('[project]') || trimmed.includes('[tool.poetry]') || trimmed.includes('[build-system]')) {
    if (trimmed.includes('[project]') || trimmed.includes('[tool.poetry]') || trimmed.includes('build-backend')) {
      return 'poetry'
    }
  }

  // requirements.txt：包含 == >= <= ~= 的包行
  if (/^[A-Za-z0-9_][A-Za-z0-9_.-]*\s*(==|>=|<=|~=|>|<)/m.test(trimmed)) {
    return 'pip'
  }

  // lockfile
  if (trimmed.startsWith('# THIS IS AN AUTOGENERATED FILE') || /^# yarn lockfile/m.test(trimmed)) {
    return 'lockfile'
  }
  if (trimmed.includes('lockfileVersion:') || trimmed.startsWith('dependencies:')) {
    return 'lockfile'
  }

  // 默认按 .env 处理
  return 'env'
}

/** 强信号文件名：扩展名/文件名本身明确指示类型，可直接采信 */
function isStrongFilename(filename: string): boolean {
  const name = filename.toLowerCase()
  return (
    name === 'package.json' ||
    name === 'requirements.txt' ||
    name.startsWith('requirements-') ||
    name === 'pyproject.toml' ||
    name === 'yarn.lock' ||
    name === 'pnpm-lock.yaml' ||
    name === 'package-lock.json'
  )
}

/** 综合检测：强信号文件名直接采信；中性文件名（.env 类/未知）优先看内容 */
export function detectProjectType(filename: string, content: string): ProjectType {
  // 强信号文件名直接采信（package.json / requirements.txt / pyproject.toml / *.lock）
  if (isStrongFilename(filename)) {
    return detectTypeByFilename(filename)!
  }
  // 中性文件名（.env 类/未知）：优先看内容，内容无法判定时再用文件名兜底
  const byContent = detectTypeByContent(content)
  if (byContent !== 'env') return byContent
  // 内容判定为 env（含默认空内容），用文件名兜底（处理 .env.production 等明确 env 文件名）
  return detectTypeByFilename(filename) ?? 'env'
}
