import { describe, it, expect } from 'vitest'
import { parseLockfile } from './lockfileParser'

describe('parseLockfile: yarn.lock', () => {
  it('extracts name, spec and locked version', () => {
    const content = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

lodash@^4.17.15:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"
  integrity sha512-...

"@babel/code-frame@^7.0.0":
  version "7.18.6"
`
    const result = parseLockfile(content, 'yarn.lock')
    expect(result.meta.format).toBe('yarn.lock v1')
    const lodash = result.dependencies.find((d) => d.name === 'lodash')
    expect(lodash?.versionSpec).toBe('^4.17.15')
    expect(lodash?.lockedVersion).toBe('4.17.21')
    const babel = result.dependencies.find((d) => d.name === '@babel/code-frame')
    expect(babel?.lockedVersion).toBe('7.18.6')
  })
})

describe('parseLockfile: pnpm-lock.yaml', () => {
  it('extracts specifier and version', () => {
    const content = `lockfileVersion: '6.0'

dependencies:
  react:
    specifier: ^18.3.1
    version: 18.3.1
`
    const result = parseLockfile(content, 'pnpm-lock.yaml')
    expect(result.meta.format).toBe('pnpm-lock.yaml')
    expect(result.dependencies[0].name).toBe('react')
    expect(result.dependencies[0].versionSpec).toBe('^18.3.1')
    expect(result.dependencies[0].lockedVersion).toBe('18.3.1')
  })
})

describe('parseLockfile: package-lock.json', () => {
  it('extracts locked versions from packages map', () => {
    const content = JSON.stringify({
      name: 'demo',
      version: '1.0.0',
      lockfileVersion: 3,
      packages: {
        '': { name: 'demo', version: '1.0.0' },
        'node_modules/react': { version: '18.3.1' },
        'node_modules/@scope/pkg': { version: '2.0.0' },
      },
    })
    const result = parseLockfile(content, 'package-lock.json')
    expect(result.meta.format).toBe('package-lock.json')
    const react = result.dependencies.find((d) => d.name === 'react')
    expect(react?.lockedVersion).toBe('18.3.1')
    const scoped = result.dependencies.find((d) => d.name === '@scope/pkg')
    expect(scoped?.lockedVersion).toBe('2.0.0')
  })
})

describe('parseLockfile: content inference + errors', () => {
  it('infers package-lock by lockfileVersion', () => {
    const result = parseLockfile('{"lockfileVersion":3,"packages":{}}', 'unknown.lock')
    expect(result.meta.format).toBe('package-lock.json')
  })

  it('adds error when nothing parsed', () => {
    const result = parseLockfile('garbage without deps', 'yarn.lock')
    expect(result.errors.length).toBeGreaterThan(0)
  })
})
